name: Build IGSideloadFix

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "16.5"
        required: true
      target_version:
        description: "Target iOS Version"
        default: "15.0"
        required: true
      decrypted_ipa_url:
        description: "Direct URL of the decrypted Instagram IPA"
        default: ""
        required: true
      rocket_zip_url:
        description: "Direct URL of Rocket zip (with Rocket.dylib + Rocket.bundle)"
        default: ""
        required: true
      upload_artifact:
        description: "Upload IPA as artifact"
        default: false
        required: false
      create_release:
        description: "Create a draft release"
        default: true
        required: false

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (skip if already installed)
        run: |
          command -v make >/dev/null || brew install make
          command -v dpkg >/dev/null || brew install dpkg
          command -v ldid >/dev/null || brew install ldid
          command -v wget >/dev/null || brew install wget
          command -v unzip >/dev/null || brew install unzip

      - name: Download Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: iOS SDK caching
        id: sdk_cache
        uses: actions/cache@v4
        with:
          path: theos/sdks/
          key: ios-sdk-${{ inputs.sdk_version }}

      - name: Download iOS SDK
        if: steps.sdk_cache.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv ./*.sdk "${THEOS}/sdks"
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Download Instagram IPA
        run: |
          wget "${{ inputs.decrypted_ipa_url }}" -O Instagram.ipa

      - name: Extract Instagram version
        run: |
          unzip -q Instagram.ipa -d tmp_ipa
          IG_VERSION=$(plutil -extract CFBundleShortVersionString raw tmp_ipa/Payload/Instagram.app/Info.plist)
          echo "IG_VERSION=$IG_VERSION" >> $GITHUB_ENV

      - name: Download Rocket zip
        run: |
          wget "${{ inputs.rocket_zip_url }}" -O rocket.zip
          unzip -q rocket.zip -d rocket_tmp
          mkdir -p ./Resources/Rocket.bundle
          cp rocket_tmp/Rocket.dylib ./Resources/
          cp -r rocket_tmp/Rocket.bundle/* ./Resources/Rocket.bundle/

      - name: Build IGSideloadFix
        run: |
          sed -i '' "s/^TARGET.*$/TARGET := iphone:clang:${{ inputs.sdk_version }}:${{ inputs.target_version }}/" Makefile
          make package FINALPACKAGE=1 CODESIGN_IPA=0
        env:
          THEOS: ${{ github.workspace }}/theos
          IG_VERSION: ${{ env.IG_VERSION }}

      - name: Rename IPA with version
        run: |
          mv ./packages/*.ipa ./packages/Instagram_sideloaded_${IG_VERSION}.ipa

      - name: Upload artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: Instagram_sideloaded_${{ env.IG_VERSION }}
          path: ./packages/Instagram_sideloaded_${{ env.IG_VERSION }}.ipa

      - name: Create draft release
        if: ${{ inputs.create_release }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.IG_VERSION }}
          name: Instagram Sideloaded v${{ env.IG_VERSION }}
          files: ./packages/Instagram_sideloaded_${{ env.IG_VERSION }}.ipa
          draft: true
