name: Build IGSideloadFix (arm64 Sideload / Unsigned)

on:
  workflow_dispatch:
    inputs:
      decrypted_ipa_url:
        description: "Direct URL of decrypted Instagram IPA"
        required: true
      rocket_zip_url:
        description: "Direct URL of Rocket.zip → extracts to Rocket.dylib + Rocket.bundle"
        required: true
      sign_ipa:
        description: "Sign the IPA? (uncheck for unsigned)"
        type: boolean
        default: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    env:
      THEOS: ${{ github.workspace }}/theos
      THEOS_JAILED: ${{ github.workspace }}/theos-jailed
      THEOS_MAKE_PATH: ${{ github.workspace }}/theos/makefiles

    steps:
      # --------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------------------------------------------
      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      # --------------------------------------------------------------
      - name: Install dependencies
        shell: bash
        run: |
          brew update --quiet
          for pkg in make llvm ldid wget unzip plutil git perl; do
            if ! command -v $pkg >/dev/null 2>&1; then
              brew install $pkg
            fi
          done
          echo "$(brew --prefix make)/libexec/gnubin" >> "$GITHUB_PATH"
          echo "$(brew --prefix llvm)/bin" >> "$GITHUB_PATH"

      # --------------------------------------------------------------
      - name: Clone Theos
        run: git clone --recursive --depth 1 https://github.com/theos/theos.git "$THEOS"

      # --------------------------------------------------------------
      - name: Clone theos-jailed (kabiroberai – defines Hackogram_INJECT_DYLIBS)
        run: git clone --recursive --depth 1 https://github.com/kabiroberai/theos-jailed.git "$THEOS_JAILED"

      - name: Install theos-jailed
        run: |
          cd "$THEOS_JAILED"
          ./install

      # --------------------------------------------------------------
      - name: Download & extract Instagram IPA
        shell: bash
        run: |
          wget -q "${{ inputs.decrypted_ipa_url }}" -O Instagram.ipa
          unzip -q Instagram.ipa -d tmp_ipa
          IG_VERSION=$(plutil -extract CFBundleShortVersionString raw tmp_ipa/Payload/Instagram.app/Info.plist)
          echo "IG_VERSION=$IG_VERSION" >> "$GITHUB_ENV"
          echo "Detected Instagram v$IG_VERSION"

      # --------------------------------------------------------------
      # ROBUST ROCKET ZIP HANDLING (fixed & complete)
      - name: Download & extract Rocket.zip (robust)
        shell: bash
        run: |
          set -euo pipefail

          INPUT="${{ inputs.rocket_zip_url }}"

          # ---- Dropbox direct-download fix ----
          if echo "$INPUT" | grep -qi "dropbox.com"; then
            if echo "$INPUT" | grep -q "dl="; then
              URL="$(echo "$INPUT" | sed -E 's/dl=[01]/dl=1/g')"
            else
              URL="${INPUT}?dl=1"
            fi
          else
            URL="$INPUT"
          fi

          echo "Downloading Rocket from: $URL"
          wget -q "$URL" -O rocket.zip

          # ---- Extract to a temporary folder ----
          rm -rf rocket_tmp
          mkdir -p rocket_tmp
          unzip -q rocket.zip -d rocket_tmp

          # ---- Find Rocket.dylib (case-insensitive) ----
          ROCKET_DYLIB=$(find rocket_tmp -type f \( -iname 'Rocket.dylib' -o -iname '*rocket*.dylib' \) | head -n1)
          if [ -z "$ROCKET_DYLIB" ]; then
            echo "Error: Rocket.dylib not found in ZIP. Contents:"
            find rocket_tmp -type f | head -20
            exit 1
          fi
          echo "Found Rocket.dylib: $ROCKET_DYLIB"

          # ---- Find Rocket.bundle (optional) ----
          ROCKET_BUNDLE=$(find rocket_tmp -type d -iname 'Rocket.bundle' | head -n1)
          if [ -n "$ROCKET_BUNDLE" ]; then
            echo "Found Rocket.bundle: $ROCKET_BUNDLE"
          else
            echo "No Rocket.bundle found (optional)."
          fi

          # ---- Copy to repo locations ----
          cp "$ROCKET_DYLIB" ./Rocket.dylib
          echo "Copied Rocket.dylib to root"

          if [ -n "$ROCKET_BUNDLE" ]; then
            mkdir -p Resources
            rm -rf Resources/Rocket.bundle
            cp -R "$ROCKET_BUNDLE" Resources/Rocket.bundle
            echo "Copied Rocket.bundle to Resources/"
          fi

          # ---- Cleanup ----
          rm -rf rocket_tmp rocket.zip
          echo "Rocket payload ready."

      # --------------------------------------------------------------
      - name: Patch Rocket.dylib (mov x0, #1 ; ret)
        shell: bash
        run: |
          set -euo pipefail
          printf '\x20\x00\x80\xd2\xc0\x03\x5f\xd6' | dd of=Rocket.dylib bs=1 seek=$((0x5E30)) conv=notrunc 2>/dev/null
          echo "Patched Rocket.dylib at offset 0x5E30"

      # --------------------------------------------------------------
      - name: Prepare Theos layout
        shell: bash
        run: |
          mkdir -p layout/Applications/Instagram.app/Frameworks
          cp -R tmp_ipa/Payload/Instagram.app/* layout/Applications/Instagram.app/
          cp Rocket.dylib layout/Applications/Instagram.app/Frameworks/
          [ -d Resources/Rocket.bundle ] && cp -R Resources/Rocket.bundle layout/Applications/Instagram.app/ || true
          echo "Theos layout ready"

      # --------------------------------------------------------------
      - name: Generate Hackogram.plist (filter)
        shell: bash
        run: |
          cat > Hackogram.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>Filter</key>
            <dict>
              <key>Bundles</key>
              <array>
                <string>com.burbn.instagram</string>
              </array>
            </dict>
          </dict>
          </plist>
          EOF
          echo "Generated Hackogram.plist"

      # --------------------------------------------------------------
      - name: Generate DEBIAN/control
        shell: bash
        run: |
          mkdir -p layout/DEBIAN
          cat > layout/DEBIAN/control <<EOF
          Package: com.momo.igsideloadfix
          Name: IGSideloadFix
          Version: ${{ env.IG_VERSION }}-1
          Architecture: iphoneos-arm
          Description: Instagram with Rocket (sideload)
          Maintainer: GitHub Actions
          Author: You
          Section: Tweaks
          Depends: firmware (>= 14.0)
          EOF
          echo "Generated DEBIAN/control"

      # --------------------------------------------------------------
      - name: Generate Makefile (tweak + jailed injection)
        shell: bash
        run: |
          cat > Makefile <<'EOF'
          ARCHS = arm64
          TARGET = iphone:clang:latest:14.0
          THEOS_PACKAGE_SCHEME = jailed

          include $(THEOS)/makefiles/common.mk

          TWEAK_NAME = Hackogram
          Hackogram_FILES = $(wildcard *.x)
          Hackogram_FRAMEWORKS = UIKit Foundation
          Hackogram_INJECT_DYLIBS = Rocket.dylib
          Hackogram_INSTALL_PATH = /Applications/Instagram.app

          include $(THEOS_MAKE_PATH)/tweak.mk
          EOF

          perl -pi -e 's/^\s+/	/' Makefile
          echo "Makefile generated"

      # --------------------------------------------------------------
      - name: Build tweak
        run: make clean

      - name: Package IPA
        run: |
          if [ "${{ inputs.sign_ipa }}" = "false" ]; then
            make package FINALPACKAGE=1 CODESIGN_IPA=0
          else
            make package FINALPACKAGE=1
          fi

      # --------------------------------------------------------------
      - name: Rename & upload IPA
        shell: bash
        run: |
          IPA=$(find packages -name "*.ipa" | head -n1)
          [ -z "$IPA" ] && { echo "IPA not found!"; ls -R packages/; exit 1; }

          SUFFIX=$( [ "${{ inputs.sign_ipa }}" = "false" ] && echo "-unsigned" || echo "" )
          NEW_NAME="IGSideloadFix-Instagram-${{ env.IG_VERSION }}$SUFFIX.ipa"
          mv "$IPA" "$NEW_NAME"
          echo "Built: $NEW_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IGSideloadFix-Instagram-${{ env.IG_VERSION }}${{ inputs.sign_ipa == false && '-unsigned' || '' }}
          path: IGSideloadFix-Instagram-${{ env.IG_VERSION }}${{ inputs.sign_ipa == false && '-unsigned' || '' }}.ipa
          retention-days: 7
