name: Build and Release IGSideloadFix

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "16.5"
        required: true
        type: string
      target_version:
        description: "Target iOS Version"
        default: "15.0"
        required: true
        type: string
      decrypted_ipa_url:
        description: "Direct URL of the decrypted Instagram IPA"
        default: ""
        required: true
        type: string
      rocket_zip_url:
        description: "Direct URL of Rocket zip containing Rocket.dylib + Rocket.bundle"
        default: ""
        required: true
        type: string

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies (if missing)
        run: |
          # Install brew packages if missing
          for pkg in make dpkg ldid wget unzip; do
            if ! brew list $pkg &>/dev/null; then
              brew install $pkg
            fi
          done
          # Install cyan if missing
          if ! python3 -c "import zule_rw" &>/dev/null; then
            pip3 install https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          fi

      - name: Download Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Generate Hackogram.plist
        run: |
          if [ ! -f Hackogram.plist ]; then
            cat <<EOF > Hackogram.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Filter</key>
    <dict>
        <key>Bundles</key>
        <array>
            <string>com.burbn.instagram</string>
        </array>
    </dict>
</dict>
</plist>
EOF
          fi

      - name: Download IPA
        run: wget "${{ github.event.inputs.decrypted_ipa_url }}" -O Instagram.ipa

      - name: Download Rocket zip
        run: |
          wget "${{ github.event.inputs.rocket_zip_url }}" -O rocket.zip
          unzip rocket.zip -d rocket_tmp
          mkdir -p ./Resources/Rocket.bundle
          cp rocket_tmp/Rocket.dylib ./Resources/
          cp -r rocket_tmp/Rocket.bundle/* ./Resources/Rocket.bundle/

      - name: Build IPA
        run: |
          sed -i '' "s/^TARGET.*$/TARGET := iphone:clang:${{ github.event.inputs.sdk_version }}:${{ github.event.inputs.target_version }}/" Makefile
          make package FINALPACKAGE=1 CODESIGN_IPA=0
        env:
          THEOS: ${{ github.workspace }}/theos
