name: Build IGSideloadFix (arm64/arm64e)

on:
  workflow_dispatch:
    inputs:
      decrypted_ipa_url:
        description: "Direct URL of the decrypted Instagram IPA"
        required: true
      rocket_deb_url:
        description: "Direct Dropbox URL of Rocket .deb (use dl=1)"
        required: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install make ldid dpkg llvm unzip wget gh || true
          echo "$(brew --prefix make)/libexec/gnubin" >> "$GITHUB_PATH"
          echo "$(brew --prefix llvm)/bin" >> "$GITHUB_PATH"

      - name: Download Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download Instagram IPA
        run: |
          wget "${{ github.event.inputs.decrypted_ipa_url }}" --no-verbose -O Instagram.ipa
          unzip -q Instagram.ipa -d tmp_ipa
          IG_VERSION=$(grep -A 1 '<key>CFBundleShortVersionString</key>' tmp_ipa/Payload/Instagram.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')
          echo "IG_VERSION=${IG_VERSION}" >> "$GITHUB_ENV"

      - name: Download Rocket ZIP
        run: wget -O rocket.zip --content-disposition "${{ github.event.inputs.rocket_deb_url }}"

      - name: Extract Rocket files
        run: unzip -q rocket.zip -d rocket_tmp

      - name: Patch Rocket dylib
        run: |
          llvm-objcopy --update-section __TEXT,__text=<(printf '\x20\x00\x80\xd2\xc0\x03\x5f\xd6') rocket_tmp/Rocket.dylib Rocket_patched.dylib
          mv Rocket_patched.dylib Rocket.dylib

      - name: Extract Rocket.bundle resources
        run: |
          BUNDLE_PATH=$(find rocket_tmp -type d -name "Rocket.bundle" | head -n1)
          if [ -z "$BUNDLE_PATH" ]; then
              echo "Error: Rocket.bundle not found in the .deb"
              exit 1
          fi
          mkdir -p Resources
          cp -R "$BUNDLE_PATH/" Resources/

      - name: Force arm64/arm64e and clean previous builds
        run: |
          sed -i '' 's/^ARCHS.*/ARCHS = arm64 arm64e/' Makefile
          sed -i '' 's/^TARGET.*/TARGET = iphone:clang:16.5:15.0/' Makefile
          sed -i '' 's/^Hackogram_INJECT_DYLIBS.*/Hackogram_INJECT_DYLIBS = Rocket.dylib/' Makefile
          make clean
          rm -rf .theos/obj/armv7
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build patched IPA
        run: make package FINALPACKAGE=1 CODESIGN_IPA=0
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IGSideloadFix-Instagram-${{ env.IG_VERSION }}
          path: packages/*.ipa

      - name: Publish GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IG_VERSION: ${{ env.IG_VERSION }}
        run: |
          RELEASE_TAG="v${IG_VERSION}-$(date +'%Y%m%d')"
          RELEASE_NAME="IGSideloadFix v${IG_VERSION} ($(date +'%Y-%m-%d'))"
          IPA_PATH=$(find packages -name "*.ipa" | head -n1)

          echo "Creating release ${RELEASE_NAME}..."

          # If release already exists, delete it first to allow overwrite
          if gh release view "$RELEASE_TAG" &>/dev/null; then
            echo "Existing release found. Deleting old release..."
            gh release delete "$RELEASE_TAG" --yes
          fi

          # Write release notes safely to a file
          cat > release_notes.txt <<EOF
Automatically built from workflow dispatch.

- Instagram version: ${IG_VERSION}
- Includes Rocket dylib patch for arm64/arm64e
- Built with Theos on macOS-latest
EOF

          # Create GitHub release
          gh release create "$RELEASE_TAG" "$IPA_PATH" \
            --title "$RELEASE_NAME" \
            --notes-file release_notes.txt
