name: Build IGSideloadFix

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "16.5"
        required: true
        type: string
      target_version:
        description: "Target iOS Version"
        default: "15.0"
        required: true
        type: string
      decrypted_ipa_url:
        description: "Direct URL of the decrypted Instagram IPA"
        default: ""
        required: true
        type: string
      rocket_zip_url:
        description: "Direct URL of Rocket ZIP (with Rocket.dylib + Rocket.bundle in root)"
        default: ""
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string
      upload_artifact:
        description: "Upload IPA as artifact"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install dependencies
        run: brew install make dpkg ldid wget unzip

      - name: Add GNU Make to PATH
        run: echo "$(brew --prefix make)/libexec/gnubin" >> "$GITHUB_PATH"

      - name: Download Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download decrypted Instagram IPA
        run: |
          wget -O main/Instagram.ipa --content-disposition "${{ inputs.decrypted_ipa_url }}"
          unzip -q main/Instagram.ipa -d main/tmp
        env:
          IPA_URL: ${{ inputs.decrypted_ipa_url }}

      - name: Download Rocket ZIP
        run: wget -O rocket.zip --content-disposition "${{ inputs.rocket_zip_url }}"
        env:
          ROCKET_ZIP_URL: ${{ inputs.rocket_zip_url }}

      - name: Extract Rocket files
        run: unzip -q rocket.zip -d rocket_tmp

      - name: Copy Rocket files
        run: |
          mkdir -p ./Resources/Rocket.bundle
          cp rocket_tmp/Rocket.dylib ./               # copy dylib to repo root
          cp -R rocket_tmp/Rocket.bundle/* ./Resources/Rocket.bundle/

      - name: Build IGSideloadFix
        run: |
          cd main
          # Set TARGET architectures to arm64 + arm64e
          sed -i '' "s/^TARGET.*$/TARGET := iphone:clang:${{ inputs.sdk_version }}:${{ inputs.target_version }}/" Makefile
          echo "ARCHS = arm64 arm64e" >> Makefile
          make package FINALPACKAGE=1 CODESIGN_IPA=0
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload IPA artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: IGSideloadFix
          path: main/packages/*.ipa
          if-no-files-found: error
